# Generated by Django 4.0 on 2023-06-22 21:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='canocinal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='descrip',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='product',
            name='normal_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='full_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='info_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='info_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
