# Generated by Django 4.0 on 2023-06-22 21:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_remove_product_alt_remove_product_canocinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_info_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='full_info_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
