# Generated by Django 4.0 on 2023-06-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_alter_shot_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'İnformations'},
        ),
    ]
